# config
logo: /images/svdb.png
keywords: "stevenzhao, web, javascript, nodejs, blog, front end, backend, fullstack, developer"
pubkey: 
menu:
  Home: /
  # Articles: /articles
  Projects: /projects
  About: /about

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analytics: UA-106933947-1
